SYMBOL = "BTCUSDT"
INTERVAL = "1m"

# First download range.
# We will expand this after confirming the downloader works.
START_DATE = "2026-01-01"

# None means update automatically up to the current UTC time.
END_DATE = None
INITIAL_BALANCE = 10_000.0

# Approximate trading costs.
COMMISSION_RATE = 0.0005
SLIPPAGE_RATE = 0.0001

FAST_EMA_LENGTH = 9
SLOW_EMA_LENGTH = 15
TREND_EMA_LENGTH = 200
ATR_LENGTH = 14
USE_EMA200_FILTER = False
TRADING_FEE_RATE = 0.0005

SLOPE_LOOKBACK = 5
MIN_FAST_SLOPE_ATR = 0.20
MIN_SLOW_SLOPE_ATR = 0.10

RISK_REWARD_RATIO = 2.0

PIN_BAR_WICK_BODY_RATIO = 2.0
PIN_BAR_MAX_OPPOSITE_WICK_RATIO = 0.75
MARUBOZU_MIN_BODY_PERCENT = 80.0

CROSSOVER_CONFIRMATION_BARS = 5